### ISSUE TITLE
Make `mainBody` behavior the default when parsing args

### ISSUE THREAD

**Issue by holgerbrandl** [xenomachina/kotlin-argparser#65] opened 2018-09-07 13:40 UTC
It took me quite a while (and frustration) to realize that my naive way of setting up a parser with
```
val args = ArgParser(args).parseInto(::MyArgs) 

```
wont give any help by default unless I wrap it with
```
val args = mainBody { ArgParser(args).parseInto(::MyArgs) }
```

Why can't `parseInto` catch the exception by default and print the help (similar to how `mainBody` works). Requiring a lambda here seems too much. A boolean parameter such as `catchEx` or similar (defaulting to to `true`) for `parseInto` seems more intuitive to me.

**Comment by xenomachina** [comment] 2018-09-07 16:58
This does seem to be a common source of confusion, so it's definitely something I want to improve. 

To answer your question, though, here's what I posted in an almost identical issue yesterday:

> the reason the "mainBody" is separate from "parseInto" is to make testing easier. `mainBody` calls `exitProcess` and also writes directly to `System.out`/`System.err`, and none of that is very easy to test. So the idea is that `mainBody` has factored out a bunch of difficult to test bits. The body you pass to `mainBody` can do nothing but call a "testableMain" method, and your tests can test that same method.

Given that, I am somewhat reluctant to have the default behavior be "make my code hard to test".

**Comment by xenomachina** [comment] 2018-09-07 16:58
Duplicate of #64

**Closed by xenomachina** 2018-09-07 16:58 UTC

**Comment by holgerbrandl** [comment] 2018-09-10 06:31
Thanks for detailing it out. Though, I personally would consider an easy and intuitive usage more important than testability. 

Btw, what I did for https://github.com/holgerbrandl/kscript which suffers from a similar conceptual problem was to combine jvm-unit-testing with  integration-level tests (error, exit codes) using `assert.sh`.
